url: "https://youtu.be/ZrZvhIJOgDU"
env_id: "ZrZvhIJOgDU"
datset_dir: "dataset"
is_stream: True
mask_path: ""
min_ratio_height: 0.2
save_front_only: False
target_size: [1920, 1080]
num_unprocessed_frames: 2
num_unsaved_frames: 2